### ISSUE TITLE
Sample ssh-ident file has syntax errors?

### ISSUE THREAD

**Issue by stnever** [ccontavalli/ssh-ident#20]
Hi!

I tried using the sample ssh-ident file described in the README, and got this error:

```
horusdev@devbox4:~$ python --version
Python 2.7.6

horusdev@devbox4:~$ ssh -T git@github.com -v
Traceback (most recent call last):
  File "/home/horusdev/bin/ssh", line 979, in <module>
    sys.exit(main(sys.argv))
  File "/home/horusdev/bin/ssh", line 939, in main
    config = Config().Load()
  File "/home/horusdev/bin/ssh", line 462, in Load
    exec(compile(open(path).read(), path, 'exec'), LOG_CONSTANTS, variables)
  File "/home/horusdev/.ssh-ident", line 47
    "SSH_OPTIONS": {
                 ^
SyntaxError: invalid syntax
```

I fiddled around in the file (sorry, I'm not too familiar with Python syntax), and had to change the following to run successfully:

```
# I dropped the quotes around SSH_OPTIONS here, and used '=' instead of ':'
SSH_OPTIONS = {
  "work": "-Xa",
  "secret": "-A"

# Dropped a trailing comma after this, not sure if it's necessary 
}

# Same here: dropped quotes around the property name, used = and dropped trailing comma
SSH_DEFAULT_OPTIONS = "-oUseRoaming=no"
```

Now it's working properly. I'm not sure if this syntax works in newer versions of Python, just wanted to give a heads-up.

Thanks!

**Comment by ccontavalli** [comment]
I just merged a fix for SSH_DEFAULT_OPTIONS, will fix SSH_OPTIONS shortly. Thanks for reporting the bug, and sorry for latency.
